- hosts: all
  gather_facts: False

  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python)

- hosts: vpn
  become: yes
  roles:
    - server
    - nodejs
    - shadowsocks
  vars:
    node_version: 6.x
    non_priviliged_user: vpn
